<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="resimler.aspx.cs" Inherits="resimler" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <title>Resimler</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="top_menu1" Runat="Server">
    <div id="ust-kapsayici5">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="top_menu2" Runat="Server">
    </div>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="icerik" Runat="Server">
    <!--Yazı metinleri kapsayıcı başlangıç-->
	<div id="yazi-metinleri-kapsayici">
		<iframe src="http://www.neredekal.com/kal_tesis_3d_xml_remote.php?r=neredekal&amp;w=1000&amp;h=400&amp;i=12671" width="1000" height="400" border="0" style="border:5px solid rgba(0, 60, 79, 0.6);; margin:50px 150px;"></iframe>
		<!-- #region Jssor Slider Begin -->

		<!-- Generated by Jssor Slider Maker Online. -->
		<!-- This demo works without jquery library. -->

		<script type="text/javascript" src="js/jssor.slider.min.js"></script>
		<!-- use jssor.slider.debug.js instead for debug -->
		<script>
		    jssor_1_slider_init = function () {

		        var jssor_1_options = {
		            $AutoPlay: true,
		            $DragOrientation: 2,
		            $PlayOrientation: 2,
		            $ArrowNavigatorOptions: {
		                $Class: $JssorArrowNavigator$
		            }
		        };

		        var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

		        //responsive code begin
		        //you can remove responsive code if you don't want the slider scales while window resizing
		        function ScaleSlider() {
		            var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
		            if (refSize) {
		                refSize = Math.min(refSize, 600);
		                jssor_1_slider.$ScaleWidth(refSize);
		            }
		            else {
		                window.setTimeout(ScaleSlider, 30);
		            }
		        }
		        ScaleSlider();
		        $Jssor$.$AddEvent(window, "load", ScaleSlider);
		        $Jssor$.$AddEvent(window, "resize", ScaleSlider);
		        $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
		        //responsive code end

		        //responsive code begin
		        //you can remove responsive code if you don't want the slider scales while window resizing
		        function ScaleSlider() {
		            var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
		            if (refSize) {
		                refSize = Math.min(refSize, 600);
		                jssor_1_slider.$ScaleWidth(refSize);
		            }
		            else {
		                window.setTimeout(ScaleSlider, 30);
		            }
		        }
		        ScaleSlider();
		        $Jssor$.$AddEvent(window, "load", ScaleSlider);
		        $Jssor$.$AddEvent(window, "resize", ScaleSlider);
		        $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
		        //responsive code end
		    };
		</script>

		<div id="jssor_1" style="position: relative;  top: 70px; left: 25%; width: 600px; height: 300px; overflow: hidden; visibility: hidden;">
			<!-- Loading Screen -->
			<div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
				<div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
				<div style="position:absolute;display:block;background:url('img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
			</div>
			<div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 600px; height: 300px; overflow: hidden;">
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-01.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-02.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-03.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-04.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-05.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-06.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-07.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-08.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-09.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-10.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-12.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-13.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-14.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/002-15.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/luce1.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/luce6.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/luce7.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/luce2.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/luce8.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/luce9.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/luce10.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/luce11.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/luce12.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/luce13.jpg" />
				</div>
				<div data-p="112.50" style="display: none;">
					<img data-u="image" src="img/luce14.jpg" />
				</div>
			</div>
			<!-- Arrow Navigator -->
			<span data-u="arrowleft" class="jssora08l" style="top:8px;left:8px;width:50px;height:50px;" data-autocenter="1"></span>
			<span data-u="arrowright" class="jssora08r" style="bottom:8px;right:8px;width:50px;height:50px;" data-autocenter="1"></span>
			<a href="http://www.jssor.com" style="display:none">Slideshow Maker</a>
		</div>
		<script>
		    jssor_1_slider_init();
		</script>

		<!-- #endregion Jssor Slider End -->
		
	</div>
	<!--Yazı metinleri kapsayıcı bitiş-->
</asp:Content>

